config/routes.rb
Rails.application.routes.draw do
  
  resources :other_articles
  resources :vehicules
  resources :electronics_computers
  resources :housings
  resources :reviews
  
  get '/tutors/home' => 'tutors#home'
  resources :tutors do
     collection do
      get 'search'
    end
  end

  get '/electronics_computers/home' => 'electronics_computers#home'
  resources :electronics_computers do
     collection do
      get 'search'
    end
  end

  get 'students/show'
  devise_for :students, controllers: { registrations: 'registrations' }
  resources :students #, only:[:update, :show, :edit]
  
  root 'books#home'
  
  resources :universities 

  resources :students do
    resources :universities do
      member do
        post 'join'
        delete 'leave'
      end
    end
  end

  resources :conversations do
    resources :messages
   end
  
  resources :books do
    resources :conversations #do
    collection do
      get 'search'
    end
  end

   

  devise_scope :students do
    get '/students/sign_out' => 'devise/sessions#destroy'
    get '/students' => 'devise/registrations#update'
  end

 

 

  

  

  
  

end

app/models/student.rb
class Student < ActiveRecord::Base

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :confirmable
         #:recoverable, :rememberable, :trackable, :validatable, :confirmable
  attr_accessor :profilepic
  has_many :books, dependent: :destroy
  has_many :tutors, dependent: :destroy
  has_many :electronics_computers, dependent: :destroy
  has_many :housings, dependent: :destroy 
  has_many :vehicules, dependent: :destroy
  has_many :other_articles, dependent: :destroy

  has_many :conversations, :foreign_key => :sender_id, dependent: :destroy
  has_many :conversations, :foreign_key => :recipient_id, dependent: :destroy
  
  has_many :join_universities_students, dependent: :destroy
  has_many :universities, through: :join_universities_students, dependent: :destroy #, source: "university"

  #has_many :joined_events, through: :events_users, source: "event"

  #validates :email, format: { with: /\.cuny.edu\z/, with:/\.suny.edu\z/, with:/\.nyu.edu\z/, message: "only allows cuny.edu addresses" }
  # has_attached_file :profilepic, styles: { medium: "300x300#", thumb: "100x100#", icon: "35x35#" }, default_url: "/images/:style/missing.jpg"
  has_attached_file :profilepic, styles: { medium: "300x300#", thumb: "100x100#", icon: "35x35#" }, default_url: "/images/:style/missing.jpg"
  validates_attachment_content_type :profilepic, content_type: /\Aimage\/.*\Z/


  def name
    [fname, lname].compact.join(' ')
  end



end   

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!  
  before_action :set_student, only:[:show, :edit, :update, :destroy]
  #before_action :authorize_admin, only: [:index]
  
# def show
#    @user = current_user 
#    @joined_events = @user.joined_events
#   end

  def show
     @student = current_student
     @book = @current_student.books

     @universities = JoinUniversitiesStudent.where("id = ?",current_student.id)

     @join_universities_students = @student.join_universities_students    
  end


  def index
      @students = Student.where.not("id = ?",current_student.id).order("created_at DESC")
      @conversations = Conversation.involving(current_student).order("created_at DESC")
  end

 

     
  def edit

  end 



  def name
    name = fname + ' '
    # name += "#{middle_initial}. " unless middle_initial.nil?
    name += lname
  end

    def destroy
    @student = Student.find(params[:id])
    @student.destroy

    if @student.destroy
        redirect_to root_url, notice: "Account deleted."
    end
  end




  private

  def set_student
    @student = Student.find_by_id(params[:student_id])
  end

  def user_params
    params.require(:student).permit(:fname, :lname, :email, :password, :password_confirmation, :current_password, :profilepic, :name, :pseudo)
  end
  


end

app/helpers/students_helper.rb
module StudentsHelper



  def conversation_interlocutor(conversation)
    conversation.recipient == current_student ? conversation.sender : conversation.recipient
  end




end

app/views/students/create.js.erb
<% publish_to @path do %>
    var id = "<%= @conversation.id %>";
    var chatbox = $("#chatbox_" + id + " .chatboxcontent");
    var sender_id = "<%= @message.student.id %>";
    var reciever_id = $('meta[name=student-id]').attr("content");

    chatbox.append("<%= j render( partial: @message ) %>");
    chatbox.scrollTop(chatbox[0].scrollHeight);

    if(sender_id != reciever_id){
    	chatBox.chatWith(id);
        chatbox.children().last().removeClass("self").addClass("other");        
    	chatbox.scrollTop(chatbox[0].scrollHeight);
        chatBox.notify();
    }
<% end %>

app/views/students/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "chat2.js" %>
<% end %>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "students.js" %>
<% end %>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "create.js.erb" , skip_pipeline: true %>
<% end %>



<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<script type="text/javascript">

if (location.href.indexOf('reload')==-1)
{
   location.href=location.href+'?reload';
}
</script>  <!-- #reload page for chatbox javascript to load -->





<div class="row">
  <% if current_student[:admin] == true %>
  <!-- Not implemented on tutorial -->
  <div class="col-md-4">
    <div style="height: 300px; overflow-y: auto;">
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Registered Students</div>

        <!-- Table -->
        <table class="table">
          <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @students.each_with_index do |student, index| %>
              <tr>
                <td><%= index +=1 %></td>
                  <% if student.name.blank? %>
                    <td><%= student.email[0...18] %></td>
                  <% else %>  
                    <td><%= student.name %></td>
                  <% end %>
                <td>
                  <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversationSimple",
                              "data-sid" => current_student.id, "data-rip" => student.id %>
                </td>
              </tr>
          <% end %>

          </tbody>
        </table>
      </div>

    </div>
    <hr>
    <% end %>
    <h3>Your Conversations</h3>

    <div style="height: 400px; overflow-y: auto;">
      <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
                <li class="media">
                  <%= image_tag("http://placehold.it/50x50", class: "media-object pull-left") %>
                  <div class="media-body">
                    <%= link_to "", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id %>
                  
                  <% if  conversation_interlocutor(conversation).present? %>
                    <% if conversation_interlocutor(conversation).pseudo.nil? %>
                      <h4 class="media-heading"><%= conversation_interlocutor(conversation).email %></h4>
                    <% else %>
                      <h4 class="media-heading"><%= conversation_interlocutor(conversation).pseudo %></h4>
                    <% end %>
                  <% else %>
                          <%= "user delete his or her account"%>
                  <% end %>

                        <p><%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                  </div>
                </li>

            <% end %>
          </ul>
      <% else %>
          <p>You have no conversations. Click send message with any user to create one.</p>
      <% end %>
    </div>

  </div>

  <div class="col-md-4">

  </div>

</div>

app/views/students/show.html.erb
<!-- ********************* Abou modification a partir en bas****************
 -->

 <%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.update', 'My Profile'] %></h1>
</div>
 
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <% if @student.profilepic? %>
          <div class="profilepic"> <%= image_tag @student.profilepic.url(:medium) %></div><br>
        <% end %>

      <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
        <ul class="nav navbar-nav">
          <li><%= link_to "Edit Profile", edit_student_registration_path(current_student) %></li>
          <li><%= link_to "Your Conversations", students_path(current_student) %></li>
          <li><%= link_to "Join an University", universities_path(current_student) %></li>

        </ul>
<!-- </div> -->

        <div class="table-responsive"></div>
        <table class="table">
          <tbody>
            <tr>
              <td><strong>First name:</strong></td>
              <td><%= @student.fname %> </td>
            </tr>
            <tr>
              <td><strong>Last name:</strong></td>
              <td><%= @student.lname %> </td>
            </tr>
            <tr>
              <td><strong>Email:</strong></td>
              <td><%=  @student.email %> </td>
            </tr>
            <tr>
              <td><strong>Pseudo:</strong></td>
              <td><%=  @student.pseudo %> </td>
            </tr>
            <tr>
              <td><strong>Your current university:</strong></td>
              <% @student.universities.each do |university|%>
                <td><%= university.name %> </td>
              <% end %>
            </tr>
          </tbody>
        </table>
        
      </div>

    </div>
  </div>

</div>
 



<div class="row">
  <h4> Your Posted Books </h4>
  <% @current_student.books.each do |book|%>
    <div class="col-sum-6 col-md-3">
      <div class="thumbnail">
        <p class="p-description">
     <!--   <%= link_to (image_tag book.avatar.url(:medium), class: 'avatar'), book %> -->
        <%= link_to (image_tag book.avatar.url(:medium)), book_path(book, continue: edit_book_path(book)) %>
      </p>
      </div>
    </div>
  <% end %>
</div>


<% if @current_student.tutors.exists? %>
<div class="row">
  <h4> Your Posted Tutoring </h4>
  <% @current_student.tutors.each do |tutor|%>
    <div class="col-sum-6 col-md-3">
      <div class="thumbnail">
        <p class="p-description">
     
        <%= link_to (image_tag tutor.photo_tutor.url(:medium)), tutor_path(tutor, continue: edit_tutor_path(tutor)) %>
      </p>
      </div>
    </div>
  <% end %>
</div>
<% end %>