config/routes.rb
Rails.application.routes.draw do
  
  resources :other_articles
  resources :vehicules
  resources :electronics_computers
  resources :housings
  resources :reviews
  
  get '/tutors/home' => 'tutors#home'
  resources :tutors do
     collection do
      get 'search'
    end
  end

  get '/electronics_computers/home' => 'electronics_computers#home'
  resources :electronics_computers do
     collection do
      get 'search'
    end
  end

  get 'students/show'
  devise_for :students, controllers: { registrations: 'registrations' }
  resources :students #, only:[:update, :show, :edit]
  
  root 'books#home'
  
  resources :universities 

  resources :students do
    resources :universities do
      member do
        post 'join'
        delete 'leave'
      end
    end
  end

  resources :conversations do
    resources :messages
   end
  
  resources :books do
    resources :conversations #do
    collection do
      get 'search'
    end
  end

   

  devise_scope :students do
    get '/students/sign_out' => 'devise/sessions#destroy'
    get '/students' => 'devise/registrations#update'
  end

 

 

  

  

  
  

end

app/models/tutor.rb
class Tutor < ApplicationRecord
	searchkick
	attr_accessor :photo_tutor
	belongs_to :student

	has_attached_file :photo_tutor, styles: { medium: "223x300#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :photo_tutor, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	scope :tutors_by_not_current_student, ->(student) { where.not(student: student) }


end
   

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  include TutorsHelper
  before_action :authenticate_student!, except:[ :show, :home]
  before_action :set_tutor, only: [:show, :edit, :update, :destroy, :home]
  
layout "tutors"
  # GET /tutors
  # GET /tutors.json
  
  # def index
  #   @tutors = Tutor.all
  # end
  

   def home
    @student = current_student
    @tutors = Tutor.all.order("created_at DESC").paginate(page: params[:page], per_page: 16)
  end

  def index
   # @book = Book.posts_by_not_current_student(current_student)
   @tutors = Tutor.where.not(student_id: current_student.id).order("created_at DESC").paginate(page: params[:page], per_page: 16)
  end



  # GET /tutors/1
  # GET /tutors/1.json
  # def show
  # end


  def show
  @tutor = Tutor.find(params[:id])
  @student = @tutor.student
  end


  # GET /tutors/new
  # def new
  #   @tutor = Tutor.new
  # end


  def new
    @tutor = current_student.tutors.build
    #@book = Book.new
  end


  # GET /tutors/1/edit
  # def edit
  # end

  def edit
    @student = current_student
    @tutor = Tutor.find(params[:id])
    #@tutor = Tutor.find_by(set_tutor)
  end

  # POST /tutors
  # POST /tutors.json
  def create
    #@tutor = Tutor.new(tutor_params)
    @tutor = current_student.tutors.build(tutor_params)
    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    @tutor = Tutor.find(params[:id])
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor = Tutor.find(params[:id])
    @tutor.destroy
    respond_to do |format|
      if @tutor.destroy
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
      #redirect_to tutor_path(@tutor)
      end
    end
  end


  def search
    if params[:search].present?
      @tutors = Tutor.search(params[:search])
    else
      @tutors = Tutor.all
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      #@tutor = Tutor.find(params[:tutor_id])
      @tutor = Tutor.find_by(params[:tutor_id])
    end

    # def set_book
    #   @book = Book.find_by(params[:book_id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:name, :degree, :classTeaching, :grades, :price, :schedule, :location, :student_id, :tutorDescription, :photo_tutor,
       :emailtutor, :availabletutor)
    end
end

app/helpers/tutors_helper.rb
module TutorsHelper

	def tutor_params
    params.require(:tutor).permit(:name, :photo_tutor)
  end
end

app/views/tutors/_form.html.erb
<!-- <%= form_with(model: tutor, local: true) do |form| %>
  <% if tutor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
      <% tutor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tutor_name %>
  </div>

  <div class="field">
    <%= form.label :degree %>
    <%= form.text_field :degree, id: :tutor_degree %>
  </div>

  <div class="field">
    <%= form.label :classTeaching %>
    <%= form.text_area :classTeaching, id: :tutor_classTeaching %>
  </div>

  <div class="field">
    <%= form.label :grades %>
    <%= form.text_area :grades, id: :tutor_grades %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :tutor_price %>
  </div>

  <div class="field">
    <%= form.label :schedule %>
    <%= form.text_area :schedule, id: :tutor_schedule %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :tutor_location %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id, id: :tutor_student_id %>
  </div>

  <div class="field">
    <%= form.label :tutorDescription %>
    <%= form.text_area :tutorDescription, id: :tutor_tutorDescription %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
-->
<!-- ------------------------------ new try below -------------------------------- -->




<%= form_for @tutor, :html => { :class => "form-horizontal book",  } do |f| %>

  <% if @tutor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@tutor.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @tutor.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div> 
  <% end %>

  <div class="form-group">
    <%= f.label :tutor_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' , placeholder: "required", :required => true %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :degree_or_level_of_education, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :degree, :class => 'form-control' %>
    </div>
    <%=f.error_span(:degree) %>
  </div>

   <div class="form-group">
    <%= f.label :Class_To_Teach, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :classTeaching, :class => 'form-control' %>
    </div>
    <%=f.error_span(:classTeaching) %>
  </div>

  <div class="form-group">
    <%= f.label :Grades_in_Class_You_want_to_Teach, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :grades, :class => 'form-control' %>
    </div>
    <%=f.error_span(:grades) %>
  </div>



  <div class="form-group">
    <%= f.label :price_per_hour, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control', placeholder: "USD", type: "number" %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <%= f.label :tutor_schedule, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :schedule, :class => 'form-control' %>
    </div>
    <%=f.error_span(:schedule) %>
  </div>

  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>

  <div class="form-group">
    <%= f.label :Tutor_Description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :tutorDescription, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tutorDescription) %>
  </div>


  <div class="form-group">
    <%= f.label :available_now, :class => 'control-label col-lg-2' %>
     
     <div class="col-lg-10">
     <%= f.radio_button :availabletutor, 'true' %> 
     <%= label :true, 'yes' %>
      <%= f.radio_button :availabletutor, 'false', :checked => true %>
      <%= label :false, 'no' %>
    </div>
    <%=f.error_span(:availabletutor) %>
  </div>

  <div class="form-group">
    <%= f.label :Tutor_email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :emailtutor, :class => 'form-control' %>
    </div>
    <%=f.error_span(:emailtutor) %>
  </div>

 

  <div class="form-group">
    <%= f.label :Tutor_Picture, class: 'col-sm-2 control-label' %>
    <div class="col-lg-10"> <!-- class="col-sm-6" -->
      <%= f.file_field :photo_tutor, :required => true, autofocus: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tutors_path, :class => 'btn btn-default' %>
    </div>
  </div> 
<% end %>

app/views/tutors/_headertutors.html.erb
<nav class= "navbar navbar-default" role="navigation">   <!-- <nav class="headernav">  -->
	<div class= "container">                
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>  
				<div class ="logo" >
                 <a class="navbar-brand" href="/">
                    <img src="/images/logo.png" alt="logo" width="50" height="40" >
                  </a> 
                </div>
			
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav" >
				<% if student_signed_in? %>
				   <!--  <span>Hello <%= current_student.email %></span> --> 
	      			<li><%= link_to "ALL TUTORS", tutors_home_path %></li>
	      			<li><%= link_to "Book a tutor", tutors_path(current_student) %></li>
	      			<li><%= link_to "Become a tutor", new_tutor_path, class: "active" %></li>
	      			<!-- <li><%= link_to "Account", edit_student_registration_path %></li>  -->
	      			<li><%= link_to "my profile", student_path(current_student) %></li>
	      			<li><%= link_to "Logout", destroy_student_session_path %></li>
	      			<!-- <h4>Hello <%= current_student.name %></h4> -->
	      		<% else %>
	      			<li><%= link_to('LOGIN', new_student_session_path)  %>
	      		<% end %>
			</ul>
			
			<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
				<p>
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for a book" %>
					<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
				</p>	
			<% end %>
		</div>
	</div> 
</nav>

app/views/tutors/edit.html.erb
<h1>Editing Tutor</h1>

<%= render 'form', tutor: @tutor %>

app/views/tutors/headertutors.html.erb
<nav class= "navbar navbar-default" role="navigation">   <!-- <nav class="headernav">  -->
	<div class= "container">                
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>  
				<div class ="logo" >
                 <a class="navbar-brand" href="/">
                    <img src="/images/logo.png" alt="logo" width="50" height="40" >
                  </a> 
                </div>
			
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav" >
				<% if student_signed_in? %>
				   <!--  <span>Hello <%= current_student.email %></span> --> 
	      			<li><%= link_to "ALL TUTORS", tutors_home_path %></li>
	      			<li><%= link_to "Book a tutor", tutors_path(current_student) %></li>
	      			<li><%= link_to "Become a tutor", new_tutor_path, class: "active" %></li>
	      			<!-- <li><%= link_to "Account", edit_student_registration_path %></li>  -->
	      			<li><%= link_to "my profile", student_path(current_student) %></li>
	      			<li><%= link_to "Logout", destroy_student_session_path %></li>
	      			<!-- <h4>Hello <%= current_student.name %></h4> -->
	      		<% else %>
	      			<li><%= link_to('LOGIN', new_student_session_path)  %>
	      		<% end %>
			</ul>
			
			<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
				<p>
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for a book" %>
					<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
				</p>	
			<% end %>
		</div>
	</div> 
</nav>

app/views/tutors/home.html.erb
<div  class= "vertivcalnacBook">

  <div class="btn-group-vertical">
  
   <Button class="btn btn-secondary"><%= link_to "Books", books_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Electronics", electronics_computers_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Tutoring", tutors_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Apartments", housings_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Cars", vehicules_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Others", other_articles_path %></Button>
  
  </div>
</div>


<% if student_signed_in? %>
 	<%- model_class = Student -%>
	<div class="page-header">
		<h1><%=t '.title', :default => [:'helpers.titles.update', 'All Tutors'] %></h1>
	</div>

	<% @tutors.each do |tutor|%>	
	<!-- <div class="p-wrap"> -->  
	    <!-- <div class="col-sum-6 col-md-3"> -->
    	<div class="p-places">
      		<div class="thumbnail">
        		<%= link_to (image_tag tutor.photo_tutor.url(:medium)), tutor_path(tutor, continue: edit_tutor_path(tutor)) %>
	        	<div class="p-description">
		          <p> <%= tutor.name %></p>
	              <p>$<%= tutor.price %></p>
	              <p> <%= tutor.classTeaching %></p>
	        	</div>
      		</div>
    	</div>
	<% end %>
<% end %>






<% if !student_signed_in? %>
	<%- model_class = Student -%>
	<div class="page-header">
	  <h1><%=t '.title', :default => [:'helpers.titles.update', 'For Sale'] %></h1>
	</div>

	      	
	<% @tutors.each do |tutor|%>
	<!-- <div class="p-wrap"> -->
		<!-- <div class="col-sum-6 col-md-3"> -->

		<div class="p-places">
			<div class="thumbnail">
        		<%= link_to (image_tag tutor.photo_tutor.url(:medium)), new_student_session_path %>
        		<div class="p-description">
	              <p> <%= tutor.name %></p>
	              <p>$<%= tutor.price %></p>
	              <p> <%= tutor.classTeaching %></p>
            	</div>
      		</div>
   		</div>
	<% end %>
<% end %>

app/views/tutors/index.html.erb
<div  class= "vertivcalnacBook">

  <div class="btn-group-vertical">
  
   <Button class="btn btn-secondary"><%= link_to "Books", books_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Electronics", electronics_computers_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Tutoring", tutors_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Apartments", housings_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Cars", vehicules_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Others", other_articles_path %></Button>
  
  </div>
</div>



<div class= "sidebar">
 <% content_for(:sidebar) do %>
  <% render :partial => "layouts/sidebar" %>

 <% end %>
</div>

 <!-- ------------------------ New work below --------------------------- -->

 <% if student_signed_in? %>
  <%- model_class = Student -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.update', 'Available Tutors'] %></h1>
  </div>

  <% @tutors.each do |tutor|%>  
  <!-- <div class="p-wrap"> -->  
      <!-- <div class="col-sum-6 col-md-3"> -->
      <div class="p-places">
          <div class="thumbnail">
            <%= link_to (image_tag tutor.photo_tutor.url(:medium)), tutor_path(tutor, continue: edit_tutor_path(tutor)) %>
            <div class="p-description">
              <p> <%= tutor.name %></p>
              <p>$<%= tutor.price %></p>
              <p> <%= tutor.classTeaching %></p>
            </div>
          </div>
      </div>
  <% end %>
<% end %>






<% if !student_signed_in? %>
  <%- model_class = Student -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.update', 'Available Tutors'] %></h1>
  </div>

          
  <% @tutors.each do |tutor|%>
  <!-- <div class="p-wrap"> -->
    <!-- <div class="col-sum-6 col-md-3"> -->

    <div class="p-places">
      <div class="thumbnail">
            <%= link_to (image_tag tutor.photo_tutor.url(:medium)), new_student_session_path %>
            <div class="p-description">
              <p> <%= tutor.title %></p>
              <p>$<%= tutor.price %></p>
              <p> <%= tutor.classTeaching %></p>
            </div>
          </div>
      </div>
  <% end %>
<% end %>




<!-- New test below --------------------- -->



<%= will_paginate(@tutors, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, previous_label: "Older", next_label: "Newer", inner_window: 1, outer_window: 0 ,class: 'justify-content-center') %>

app/views/tutors/new.html.erb
<h1>New Tutor</h1>

<%= render 'form', tutor: @tutor %>

<%= link_to 'Back', tutors_path %>

app/views/tutors/show.html.erb
<!-- ----------------------------- new try below -------------------------------- -->

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "chat.js" %>
<% end %>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "books.js" %>
<% end %>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "create.js.erb" , skip_pipeline: true %>
<% end %>




<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<script type="text/javascript">

if (location.href.indexOf('reload')==-1)
{
   location.href=location.href+'?reload';
}
</script>  <!-- #reload page for chatbox javascript to load -->



<!-- ********************* Abou modification a partir en bas****************
 -->

 <%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.update', 'For Sale'] %></h1>
</div>
 
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @tutor.photo_tutor.url(:medium) %>
        <div class="table-responsive"></div>
        <table class="table">
          <tbody>
            <tr>
              <td><strong>Name:</strong></td>
              <td><%= @tutor.name %> </td>
            </tr>
            <tr>
              <td><strong>Degree or Level of Education:</strong></td>
              <td><%= @tutor.degree %> </td>
            </tr>
            <tr>
              <td><strong>Price per Hour:</strong></td>
              <td>$ <%=  @tutor.price %> </td>
            </tr>
            <tr>
              <td><strong>Class To Teach:</strong></td>
              <td>$ <%=  @tutor.classTeaching %> </td>
            </tr>


            <tr>
              <td><strong>Available Now:</strong></td>
              <% if @tutor.availabletutor? %>
                <td> Yes </td>
              <% else %>
                <td> No </td>
              <% end %>
            </tr>


            <tr>
              <td><strong>Schedule:</strong></td>
              <td><%= @tutor.schedule %> </td>
            </tr>
            <tr>

            <tr>
              <td><strong>tutor description:</strong></td>
              <td><%= @tutor.tutorDescription %> </td>
            </tr>
            <tr>
              <td><strong>Tutor email:</strong></td>
              <td><%= @tutor.emailtutor %> </td>
            </tr>

          </tbody>
        </table>
        
      </div>

    </div>
  </div>

</div>
 
  <%  if (student_signed_in? && (current_student.id == @tutor.student_id)) %>

            <%= link_to t('.back', :default => t("helpers.links.back")),
                          tutors_path, :class => 'btn btn-default'  %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_tutor_path(@tutor), :class => 'btn btn-default' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          tutor_path(@tutor),
                          :method => 'delete',
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-danger' %>
  
  

  <% end %>



<% if student_signed_in? && current_student.id != @tutor.student_id %>  <!-- good one here -->

           <%= link_to "Send Message to Owner", "#", class: "btn btn-success btn-xs start-conversation",
                              "data-sid" => current_student.id, "data-rip" =>  @tutor.student_id %>

<% end -%>

<!--
<% if student_signed_in? && current_student.id != @tutor.student_id %>  <!-- good one here -->

<!--           <%= link_to "Send Message to Owner", "#", class: "btn btn-success btn-xs start-conversation",
                              "data-sid" => current_student.id, "data-rip" =>  @tutor.student_id %>

<% end -%>
-->