config/routes.rb
Rails.application.routes.draw do
  
  resources :other_articles
  resources :vehicules
  resources :electronics_computers
  resources :housings
  resources :reviews
  
  get '/tutors/home' => 'tutors#home'
  resources :tutors do
     collection do
      get 'search'
    end
  end

  get '/electronics_computers/home' => 'electronics_computers#home'
  resources :electronics_computers do
     collection do
      get 'search'
    end
  end

  get 'students/show'
  devise_for :students, controllers: { registrations: 'registrations' }
  resources :students #, only:[:update, :show, :edit]
  
  root 'books#home'
  
  resources :universities 

  resources :students do
    resources :universities do
      member do
        post 'join'
        delete 'leave'
      end
    end
  end

  resources :conversations do
    resources :messages
   end
  
  resources :books do
    resources :conversations #do
    collection do
      get 'search'
    end
  end

   

  devise_scope :students do
    get '/students/sign_out' => 'devise/sessions#destroy'
    get '/students' => 'devise/registrations#update'
  end

 

 

  

  

  
  

end

app/views/layouts/_header.html.erb
<nav class= "navbar navbar-default" role="navigation">   <!-- <nav class="headernav">  -->
	<div class= "container">                
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>  
			
			<div class ="logo" >
            	<a class="navbar-brand" href="/">
                	<img src="/images/logo.png" alt="logo" width="50" height="40" >
            	</a> 
            </div>
              
		<!-- <span style="color:#28476E;"><span style="font-family:wfont_f272c6_05cbcee10282439b80a73a36a7defdd8, wf_05cbcee10282439b80a73a36a, orig_graphiksemibold; font-weight:200; font-size: xx-large;">Cunyversity</span></span> -->
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav" >
				<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-center", role: "search" do %>
					<p>
						<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for a book" %>
						<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
					</p>
				<% end %>
			</ul>
			
			<ul class="nav navbar-nav" >
				<% if student_signed_in? %>
				   <!--  <span>Hello <%= current_student.email %></span> --> 
	      			<li><%= link_to "ALL BOOKS", root_path %></li>
	      			<li><%= link_to "Buy books", books_path(current_student) %></li>
	      			<li><%= link_to "Sell your Book", new_book_path, class: "active" %></li>
	      			<!-- <li><%= link_to "Account", edit_student_registration_path %></li>  -->
	      			<li><%= link_to "my profile", student_path(current_student) %></li>
	      			<li><%= link_to "Logout", destroy_student_session_path %></li>
	      			<!-- <h4>Hello <%= current_student.name %></h4> -->
	      		<% else %>
	      			<li><%= link_to('LOGIN', new_student_session_path)  %></li>
	      		<% end %>
			</ul>


		</div>
	</div> 
</nav>



<!-- ----------------------- new example below ---------------- -->





<div style="float:right; margin-right: 5px;" >
	<% if student_signed_in? %>
		<h4>Welcome, <%= current_student.fname %></h4>
	<% end %>
 
</div>

app/views/layouts/_sidebar.html.erb
<div  class= "vertivcalnac">

 	<div class="btn-group-vertical">
  
	<Button class="btn btn-secondary"><%= link_to "Books", books_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Electronics", electronics_computers_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Tutoring", tutors_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Apartments", housings_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Cars", vehicules_path %></Button>
    <Button class="btn btn-secondary"><%= link_to "Others", other_articles_path %></Button>
  
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta content='<%= student_signed_in? ? current_student.id : "" %>' name='student-id'/>
    <title>Cunyversity</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "http://cunyversity.com/faye.js" %>
  <!--   <%= csrf_meta_tags %> -->
  	 
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <script>
           (adsbygoogle = window.adsbygoogle || []).push({
                google_ad_client: "ca-pub-3837471042049839",
              enable_page_level_ads: true
         });
    </script>
  </head>

  <body>



    <%= render 'layouts/header' %>
   <!--  <%= render 'layouts/sidebar' %> -->


    <div>
        <%= yield :sidebar %>
    </div>
    
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
     <%= yield %>
     </div>
      
  </body>
</html>





 

app/views/layouts/books.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta content='<%= student_signed_in? ? current_student.id : "" %>' name='student-id'/>
    <title>Cunyversity</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar' %>

  	<div>
      
  		<%= yield :sidebar %>
  	</div>

    <div class="container">
  		<% flash.each do |name, msg| %>
    	  <%= content_tag(:div, msg, class: "alert alert-info") %>
  	  <% end %>
  			<%= yield %>
  	</div>
      
  </body>
</html>

app/views/layouts/electronics.html.erb
 <!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= student_signed_in? ? current_student.id : "" %>' name='student-id'/>
  <title>Cunyversity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 
 <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-3837471042049839",
          enable_page_level_ads: true
     });
</script>
</head>

<body>


<nav class= "navbar navbar-default" role="navigation">   <!-- <nav class="headernav">  -->
	<div class= "container">                
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>  
				<div class ="logo" >
                 <a class="navbar-brand" href="/">
                    <img src="/images/logo.png" alt="logo" width="50" height="40" >
                  </a> 
                </div>
			
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav" >
				<% if student_signed_in? %>
				   <!--  <span>Hello <%= current_student.email %></span> --> 
	      			<li><%= link_to "All Electronics and Computers", electronics_computers_path %></li>
	      			<li><%= link_to "Rent or Buy a device", electronics_computers_path(current_student) %></li>
	      			<li><%= link_to "Sell or Rent your device", new_electronics_computer_path, class: "active" %></li>
	      			<!-- <li><%= link_to "Account", edit_student_registration_path %></li>  -->
	      			<li><%= link_to "my profile", student_path(current_student) %></li>
	      			<li><%= link_to "Logout", destroy_student_session_path %></li>
	      			<!-- <h4>Hello <%= current_student.name %></h4> -->
	      		<% else %>
	      			<li><%= link_to('LOGIN', new_student_session_path)  %>
	      		<% end %>
			</ul>
			
			<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
				<p>
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for a book" %>
					<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
				</p>	
			<% end %>
		</div>
	</div> 
</nav>



	
 <!-- test is happening here ------------------------------------------------ -->
<header>


</header>

  











<!-- test is end here ------------------------------------------------ -->

  <div>
      <%= yield :sidebar %>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
   <%= yield %>
   </div>
    
</body>
</html>

















  
<!-- ----------------------- new example below ---------------- -->





<div style="float:right; margin-right: 5px;" >
<% if student_signed_in? %>
	<h4>Welcome, <%= current_student.fname %></h4>
<% end %>
 


</div>

app/views/layouts/housings.html.erb
 <!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= student_signed_in? ? current_student.id : "" %>' name='student-id'/>
  <title>Cunyversity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-3837471042049839",
          enable_page_level_ads: true
     });
</script>
</head>

<body>


<nav class= "navbar navbar-default" role="navigation">   <!-- <nav class="headernav">  -->
	<div class= "container">                
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>  
				<div class ="logo" >
                 <a class="navbar-brand" href="/">
                    <img src="/images/logo.png" alt="logo" width="50" height="40" >
                  </a> 
                </div>
			
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav" >
				<% if student_signed_in? %>
				   <!--  <span>Hello <%= current_student.email %></span> --> 
	      			<li><%= link_to "ALL HOUSINGS", housings_path %></li>
	      			<li><%= link_to "Rent or Buy an apartment", housings_path(current_student) %></li>
	      			<li><%= link_to "Sell or Rent your apartment", new_housing_path, class: "active" %></li>
	      			<!-- <li><%= link_to "Account", edit_student_registration_path %></li>  -->
	      			<li><%= link_to "my profile", student_path(current_student) %></li>
	      			<li><%= link_to "Logout", destroy_student_session_path %></li>
	      			<!-- <h4>Hello <%= current_student.name %></h4> -->
	      		<% else %>
	      			<li><%= link_to('LOGIN', new_student_session_path)  %>
	      		<% end %>
			</ul>
			
			<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
				<p>
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for a book" %>
					<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
				</p>	
			<% end %>
		</div>
	</div> 
</nav>



	
 <!-- test is happening here ------------------------------------------------ -->
<header>


</header>

  











<!-- test is end here ------------------------------------------------ -->

  <div>
      <%= yield :sidebar %>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
   <%= yield %>
   </div>
    
</body>
</html>

















  
<!-- ----------------------- new example below ---------------- -->





<div style="float:right; margin-right: 5px;" >
<% if student_signed_in? %>
	<h4>Welcome, <%= current_student.fname %></h4>
<% end %>
 


</div>

app/views/layouts/others.html.erb
 <!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= student_signed_in? ? current_student.id : "" %>' name='student-id'/>
  <title>Cunyversity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-3837471042049839",
          enable_page_level_ads: true
     });
</script>
</head>

<body>


<nav class= "navbar navbar-default" role="navigation">   <!-- <nav class="headernav">  -->
	<div class= "container">                
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>  
				<div class ="logo" >
                 <a class="navbar-brand" href="/">
                    <img src="/images/logo.png" alt="logo" width="50" height="40" >
                  </a> 
                </div>
			
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav" >
				<% if student_signed_in? %>
				   <!--  <span>Hello <%= current_student.email %></span> --> 
	      			<li><%= link_to "All Others Articles", other_articles_path%></li>
	      			<li><%= link_to "Rent Other Article", other_articles_path(current_student) %></li>
	      			<li><%= link_to "Sell your Other Article", new_other_article_path, class: "active" %></li>
	      			<!-- <li><%= link_to "Account", edit_student_registration_path %></li>  -->
	      			<li><%= link_to "my profile", student_path(current_student) %></li>
	      			<li><%= link_to "Logout", destroy_student_session_path %></li>
	      			<!-- <h4>Hello <%= current_student.name %></h4> -->
	      		<% else %>
	      			<li><%= link_to('LOGIN', new_student_session_path)  %>
	      		<% end %>
			</ul>
			
			<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
				<p>
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for a book" %>
					<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
				</p>	
			<% end %>
		</div>
	</div> 
</nav>



	
 <!-- test is happening here ------------------------------------------------ -->
<header>


</header>

  











<!-- test is end here ------------------------------------------------ -->

  <div>
      <%= yield :sidebar %>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
   <%= yield %>
   </div>
    
</body>
</html>

















  
<!-- ----------------------- new example below ---------------- -->





<div style="float:right; margin-right: 5px;" >
<% if student_signed_in? %>
	<h4>Welcome, <%= current_student.fname %></h4>
<% end %>
 


</div>

app/views/layouts/tutors.html.erb
 <!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= student_signed_in? ? current_student.id : "" %>' name='student-id'/>
  <title>Cunyversity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= csrf_meta_tags %>
</head>

<body>


<nav class= "navbar navbar-default" role="navigation">   <!-- <nav class="headernav">  -->
	<div class= "container">                
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>  
				<div class ="logo" >
                 <a class="navbar-brand" href="/">
                    <img src="/images/logo.png" alt="logo" width="50" height="40" >
                  </a> 
                </div>
			
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav" >
				<% if student_signed_in? %>
				   <!--  <span>Hello <%= current_student.email %></span> --> 
	      			<li><%= link_to "ALL TUTORS", tutors_home_path %></li>
	      			<li><%= link_to "Book a tutor", tutors_path(current_student) %></li>
	      			<li><%= link_to "Become a tutor", new_tutor_path, class: "active" %></li>
	      			<!-- <li><%= link_to "Account", edit_student_registration_path %></li>  -->
	      			<li><%= link_to "my profile", student_path(current_student) %></li>
	      			<li><%= link_to "Logout", destroy_student_session_path %></li>
	      		<% else %>
	      			<li><%= link_to('LOGIN', new_student_session_path)  %>
	      		<% end %>
			</ul>
			
			<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
				<p>
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for a tutor" %>
					<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
				</p>	
			<% end %>
		</div>
	</div> 
</nav>




  <div>
      <%= yield :sidebar %>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
   <%= yield %>
   </div>
    
</body>
</html>

app/views/layouts/vehicules.html.erb
 <!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= student_signed_in? ? current_student.id : "" %>' name='student-id'/>
  <title>Cunyversity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-3837471042049839",
          enable_page_level_ads: true
     });
</script>
</head>

<body>


<nav class= "navbar navbar-default" role="navigation">   <!-- <nav class="headernav">  -->
	<div class= "container">                
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>  
				<div class ="logo" >
                 <a class="navbar-brand" href="/">
                    <img src="/images/logo.png" alt="logo" width="50" height="40" >
                  </a> 
                </div>
			
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav" >
				<% if student_signed_in? %>
				   <!--  <span>Hello <%= current_student.email %></span> --> 
	      			<li><%= link_to "All Cars", vehicules_path %></li>
	      			<li><%= link_to "Rent or Buy a car", vehicules_path(current_student) %></li>
	      			<li><%= link_to "Sell your car", new_vehicule_path, class: "active" %></li>
	      			<!-- <li><%= link_to "Account", edit_student_registration_path %></li>  -->
	      			<li><%= link_to "my profile", student_path(current_student) %></li>
	      			<li><%= link_to "Logout", destroy_student_session_path %></li>
	      			<!-- <h4>Hello <%= current_student.name %></h4> -->
	      		<% else %>
	      			<li><%= link_to('LOGIN', new_student_session_path)  %>
	      		<% end %>
			</ul>
			
			<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
				<p>
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for a book" %>
					<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
				</p>	
			<% end %>
		</div>
	</div> 
</nav>



	
 <!-- test is happening here ------------------------------------------------ -->
<header>


</header>

  











<!-- test is end here ------------------------------------------------ -->

  <div>
      <%= yield :sidebar %>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
   <%= yield %>
   </div>
    
</body>
</html>

















  
<!-- ----------------------- new example below ---------------- -->





<div style="float:right; margin-right: 5px;" >
<% if student_signed_in? %>
	<h4>Welcome, <%= current_student.fname %></h4>
<% end %>
 


</div>